name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run build
      run: ./build.sh --registry --organisation i3oot --tag latest

    - uses: docker/build-push-action@v1
      with:
        username: _json_key
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ""
        repository: i3oot/che-devfile-registry
        tags: latest
