name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
   
    - name: List files
      run: find -type f 

    - name: Run build
      run: ./build.sh  --registry  --organization i3oot --tag latest

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push i3oot/che-devfile-registry:latest


